// Bump `version` whenever question framing changes — stamped on every submission
// so historical contributions remain interpretable.
export const EXPERIENCE_CONFIG = {
  version: 1,
  maxEarthFillContributions: parseInt(process.env.MAX_EARTH_FILL_CONTRIBUTIONS ?? '10000', 10),
  voices: {
    sampleSize: 20,
    cacheSeconds: 30,
  },
  rateLimit: {
    contributeRpm: parseInt(process.env.RATE_LIMIT_CONTRIBUTE_RPM ?? '5', 10),
  },
  copy: {
    arrival: {
      line1: 'Where are we',
      line2: 'going?',
      cta: 'Add my light',
    },
    mission: {
      line1: 'What do you want',
      line2: "our Earth's mission to be?",
      placeholders: [
        'To love, and keep learning how to love better…',
        'To be a place where every being belongs…',
        'To grow wise enough to deserve this gift…',
        'To heal what has been broken and tend what is fragile…',
        'To return to wonder, and never fully leave…',
        'To remember we are one species on one planet…',
        'To create beauty worth protecting…',
        'To pass on more than we inherited…',
        'To listen before we speak, and speak when it matters…',
        'To hold the long view when it costs us something…',
        "To see every stranger as someone's beloved…",
        'To live within what the earth can carry…',
        'To discover what is possible when we stop competing…',
        'To make repair as natural as harm…',
        'To give the future a seat at every table…',
        'To find the thread of care that runs through all things…',
        "To be curious about what we don't yet understand…",
        'To honour the wild that remains…',
        'To raise children who are not afraid of each other…',
        'To trade certainty for connection…',
      ],
      cta: 'Add my vision',
      label: "Earth's mission",
    },
    principles: {
      line1: 'What values & principles would',
      line2: 'make that mission real?',
      placeholder: 'No shame…',
      cta: 'Continue',
      label: 'A value',
      seeds: [
        'Care precedes transaction',
        'Repair over perfection',
        'Curiosity over certainty',
        'Presence as practice',
        'Long-term thinking',
        'Interdependence',
        'Truth-telling as kindness',
        'Local action',
      ],
    },
    commitment: {
      line1: 'One thing you will do',
      line2: 'this week.',
      placeholder: 'Call my father. Actually listen this time.',
      cta: 'Submit yours to see everyone else’s',
      label: 'Your commitment this week',
    },
    joining: {
      line1: 'Your light is joining',
      line2: 'the earth.',
    },
    reveal: {
      voicesRegionLabel: 'Visions from around the world',
      copyLink: 'Copy link',
      copied: 'Copied ✓',
      returnHint: 'Come back soon — new lights are joining every day.',
      modeToggleMission: 'Mission',
      modeToggleValues: 'Values',
      exploreAll: 'Explore all visions',
      exploreCollapse: 'Show less',
    },
    return: {
      line1: 'What is your mission',
      line2: 'today?',
      placeholders: [
        'To slow down enough to notice what is already here…',
        'To show up fully for what is in front of me…',
        'To say the thing I have been putting off…',
        'To rest without guilt today…',
        'To see one person clearly…',
        'To carry less and give more…',
        'To begin the thing I keep waiting to begin…',
        'To tend one small relationship…',
        'To let today be enough…',
        "To notice what I'm grateful for before I need it…",
        'To listen more than I speak…',
        'To move my body like it is borrowed…',
        'To do one thing that frightens me a little…',
        "To forgive something I've been holding…",
        'To spend one hour outside…',
        'To cook for someone…',
        'To set my phone down and look up…',
        "To write the letter I've been composing in my head…",
        'To ask for help with something…',
        'To be kinder to myself than yesterday…',
      ],
      cta: 'Add to the earth',
      label: 'Your mission today',
      earthHolds: 'The earth holds every season of you.',
    },
  },
} as const

export type ExperienceConfig = typeof EXPERIENCE_CONFIG
